---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r, warning=FALSE, message=FALSE}
library(ggplot2)
library(scales)
library(Hmisc)

if(!file.exists('activity.csv')){
  unzip('activity.zip')
}

data <- read.csv('activity.csv',header=TRUE)
head(data)
data_wona<-na.omit(data)
```

## What is mean total number of steps taken per day?
```{r}
steps_total<-aggregate(steps ~ date,data_wona,sum)
hist(steps_total$steps,xlab = "Total daily steps",main="Histogram of the total number of steps taken each day", breaks = 20, col="lightsteelblue")

steps_mean<-mean(steps_total$steps)
print(paste0("mean of the total number of steps taken per day: ", steps_mean))

steps_median<-median(steps_total$steps)
print(paste0("median of the total number of steps taken per day: ", steps_median))
```
## What is the average daily activity pattern?
```{r}
steps_int<-aggregate(steps ~ interval,data_wona,mean)

plot(steps_int$interval,steps_int$steps,type="l",col="red",main = "Mean average steps", xlab = "Interval", ylab = "Steps")
steps_int[steps_int$steps==max(steps_int$steps),]
```

## Imputing missing values
```{r}

sum(is.na(data))

data_imp<-data
miss<-is.na(data$steps)
data_imp$steps[miss==TRUE] <- steps_mean / nrow(steps_int)

steps_total_imp<-aggregate(steps ~ date,data_imp,sum)
hist(steps_total_imp$steps,xlab = "Total daily steps",main="Histogram of the total number of steps taken each day", breaks = 20, col="blue")

steps_mean_imp<-mean(steps_total_imp$steps)
print(paste0("mean of the total number of steps taken per day: ", steps_mean_imp))

steps_median_imp<-median(steps_total_imp$steps)
print(paste0("median of the total number of steps taken per day: ", steps_median_imp))

steps_mean == steps_mean_imp
steps_mean > steps_mean_imp
steps_mean < steps_mean_imp

steps_median == steps_median_imp
steps_median > steps_median_imp
steps_median < steps_median_imp
```

## Are there differences in activity patterns between weekdays and weekends?
```{r}
data_imp$wd <- ifelse(weekdays(as.Date(data_imp$date)) %in% c("Samstag","Sonntag"), "weekend", "weekday")
head(data_imp)
steps_int_wd <- aggregate(steps ~ interval + wd, data_imp, mean)

ggplot(steps_int_wd, aes(interval, steps,colour=factor(wd))) + 
  geom_line() + 
  facet_grid(wd ~ .) +
 labs(title = "Mean average steps", x = "Interval", y = "Steps")
  

```
